version: '3'

name: "interview-task"

services:
  core:
    build:
      dockerfile: ./services/core/Dockerfile
      context: ./
    container_name: core
    ports:
      - 6001:6001
    depends_on:
      - price_generator
      - auth_generator
      - interview_db
    env_file: .env_example
    command: sh -c "sleep 5 && make goose-up-docker && ./core"
  price_generator:
    build:
      dockerfile: ./services/price_generator/Dockerfile
      context: ./
    container_name: price_generator
    restart: always
    ports:
      - 6002:6002
    volumes:
      - ./upload/price_pdf_files:/app/upload/price_pdf_files
      - ./docs/price_generator:/app/docs/price_generator
    env_file: .env_example
  auth_generator:
    image: andrianovartemii/gm-test-task-auth-generator:amd
    container_name: auth_generator
    restart: always
    ports:
      - 6003:8080
    env_file: .env_example
    platform: linux/arm64/v8
  interview_db:
    image: postgres:15.1-alpine3.17
    container_name: interview_db
    restart: always
    ports:
      - 6004:5432
    env_file: .env_example